name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.head_commit.message, 'chore: release v') }}"

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun and dependencies
        uses: ./.github/actions/setup

      - name: Run all checks
        run: bun run check:all

      - name: Publish to NPM
        uses: changesets/action@v1
        with:
          publish: bun run release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
